import { z } from 'zod';
import { IdSchema } from './ids.js';
import { StateOriginSchema } from './state.js';

/**
 * Command lifecycle
 * -----------------
 * pending    created; no agent has been handed it yet (e.g. none online)
 * dispatched sent to an agent over the wire
 * acked      agent confirmed receipt and started work
 * succeeded  agent reported the hardware reached the requested state
 * failed     agent reported an error
 * timed-out  no terminal response within the deadline
 * superseded a newer command for the same target replaced this one
 *
 * Command ids are generated by the *caller* and are idempotency keys: replaying
 * a command id must never perform the action twice.
 */
export const CommandStatusSchema = z.enum([
  'pending',
  'dispatched',
  'acked',
  'succeeded',
  'failed',
  'timed-out',
  'superseded',
]);
export type CommandStatus = z.infer<typeof CommandStatusSchema>;

export const IN_FLIGHT_STATUSES: readonly CommandStatus[] = ['pending', 'dispatched', 'acked'];
export const TERMINAL_STATUSES: readonly CommandStatus[] = [
  'succeeded',
  'failed',
  'timed-out',
  'superseded',
];

export function isInFlight(status: CommandStatus): boolean {
  return IN_FLIGHT_STATUSES.includes(status);
}

export function isTerminal(status: CommandStatus): boolean {
  return TERMINAL_STATUSES.includes(status);
}

export const SetMonitorInputCommandSchema = z.object({
  kind: z.literal('set-monitor-input'),
  monitorId: IdSchema,
  inputId: IdSchema,
  /** Denormalised for logging/UI; authority is inputId. */
  sourceComputerId: IdSchema.nullable().default(null),
});

/** VCP 0x10. Value is a percentage; providers scale it to the panel's range. */
export const SetMonitorBrightnessCommandSchema = z.object({
  kind: z.literal('set-monitor-brightness'),
  monitorId: IdSchema,
  brightness: z.number().int().min(0).max(100),
});

/**
 * VCP 0xD6. Deliberately three named states rather than raw VCP values: which
 * numeric code means "off" varies by panel, so the provider picks one the
 * monitor actually advertises.
 */
export const MonitorPowerStateSchema = z.enum(['on', 'standby', 'off']);
export type MonitorPowerState = z.infer<typeof MonitorPowerStateSchema>;

export const SetMonitorPowerCommandSchema = z.object({
  kind: z.literal('set-monitor-power'),
  monitorId: IdSchema,
  powerState: MonitorPowerStateSchema,
});

export const SetPeripheralOwnerCommandSchema = z.object({
  kind: z.literal('set-peripheral-owner'),
  switchId: IdSchema,
  channelId: IdSchema,
  portId: IdSchema,
  peripheralIds: z.array(IdSchema).default([]),
  ownerComputerId: IdSchema,
});

export const CommandPayloadSchema = z.discriminatedUnion('kind', [
  SetMonitorInputCommandSchema,
  SetMonitorBrightnessCommandSchema,
  SetMonitorPowerCommandSchema,
  SetPeripheralOwnerCommandSchema,
]);
export type CommandPayload = z.infer<typeof CommandPayloadSchema>;
export type CommandKind = CommandPayload['kind'];

export const CommandErrorSchema = z.object({
  code: z.string(),
  message: z.string(),
  retryable: z.boolean().default(false),
});
export type CommandError = z.infer<typeof CommandErrorSchema>;

export const DeskCommandSchema = z.object({
  id: IdSchema,
  payload: CommandPayloadSchema,
  status: CommandStatusSchema,
  origin: StateOriginSchema,
  presetId: IdSchema.nullable().default(null),
  /** Agent chosen to execute it; null while pending. */
  agentId: IdSchema.nullable().default(null),
  issuedAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  deadlineAt: z.string().datetime(),
  attempts: z.number().int().nonnegative().default(0),
  error: CommandErrorSchema.nullable().default(null),
});
export type DeskCommand = z.infer<typeof DeskCommandSchema>;

/**
 * The target a command acts on, used to supersede stale commands.
 *
 * Brightness, power and input are separate targets on the same monitor on
 * purpose: dimming a panel must not cancel an input switch that is still in
 * flight, and vice versa.
 */
export function commandTargetKey(payload: CommandPayload): string {
  switch (payload.kind) {
    case 'set-monitor-input':
      return `monitor:${payload.monitorId}:input`;
    case 'set-monitor-brightness':
      return `monitor:${payload.monitorId}:brightness`;
    case 'set-monitor-power':
      return `monitor:${payload.monitorId}:power`;
    case 'set-peripheral-owner':
      return `switch:${payload.switchId}:${payload.channelId}`;
  }
}

/** Command kinds an agent carries out against a monitor. */
export const MONITOR_COMMAND_KINDS = [
  'set-monitor-input',
  'set-monitor-brightness',
  'set-monitor-power',
] as const satisfies readonly CommandKind[];
